In [ ]:
# default_exp calib.greg

# Greg's input
> Tools and tables from Greg about calibration

In [ ]:
# export
from fastcore.utils import Path

import pandas as pd
from planetarypy.utils import nasa_datetime_to_iso
from pyuvis.pds import CatalogFilter
from pyuvis.io import UVISObs

In [ ]:
# export
def get_star_obs():
    "Read Greg's file into dataframe and add some meta-columns."
    star_list = Path(
        "/home/maye/Dropbox/Documents/projects/uvis_pdart/calib/stars_list.txt"
    )
    star_obs = pd.read_table(
        star_list, sep="\s\s+", index_col=False, engine="python"
    )  # engine kw to avoid warning

    star_obs["detector"] = star_obs.filename.str[:3]
    star_obs["filename_time"] = star_obs.filename.map(
        lambda x: nasa_datetime_to_iso(
            x[3:20].replace("_", "-", 1).replace("_", "T", 1).replace("_", ":")
        )
    )
    star_obs.filename_time = pd.to_datetime(star_obs.filename_time)
    star_obs["date"] = pd.DatetimeIndex(star_obs.filename_time.dt.date)
    star_obs["product_id"] = star_obs['filename'].str[:17]
    return star_obs

In [ ]:
df = get_star_obs()
df.head()

,filename,slit,nx,ny,nz,int,odcid,x1,x2,y1,y2,name,detector,filename_time,date,product_id
0,EUV1999_016_19_47_15,2,1024,64,2,60,12,0,1023,0,63,alp vir,EUV,1999-01-16 19:47:15,1999-01-16,EUV1999_016_19_47
1,EUV1999_016_19_49_06,2,1024,1,123,1,13,0,1023,0,63,alp vir,EUV,1999-01-16 19:49:06,1999-01-16,EUV1999_016_19_49
2,EUV1999_016_20_08_10,2,1,64,399,1,11,0,1023,0,63,alp vir,EUV,1999-01-16 20:08:10,1999-01-16,EUV1999_016_20_08
3,EUV1999_016_20_16_14,2,1024,64,2,60,12,0,1023,0,63,alp vir,EUV,1999-01-16 20:16:14,1999-01-16,EUV1999_016_20_16
4,EUV1999_016_20_18_06,2,1024,1,123,1,13,0,1023,0,63,alp vir,EUV,1999-01-16 20:18:06,1999-01-16,EUV1999_016_20_18

In [ ]:
df[df.duplicated(subset="product_id", keep=False)]

,filename,slit,nx,ny,nz,int,odcid,x1,x2,y1,y2,name,detector,filename_time,date,product_id
107,EUV2001_299_20_44_21_0,1,1024,32,233,30,98,0,1023,32,63,alp vir,EUV,2001-10-26 20:44:21,2001-10-26,EUV2001_299_20_44
108,EUV2001_299_20_44_21_1,1,8,1,233,30,98,0,1023,0,31,alp vir,EUV,2001-10-26 20:44:21,2001-10-26,EUV2001_299_20_44
109,EUV2001_299_22_41_51_1,1,8,1,234,30,97,0,1023,0,15,alp vir,EUV,2001-10-26 22:41:51,2001-10-26,EUV2001_299_22_41
110,EUV2001_299_22_41_51_0,1,1024,32,234,30,97,0,1023,16,47,alp vir,EUV,2001-10-26 22:41:51,2001-10-26,EUV2001_299_22_41
111,EUV2001_299_22_41_51_2,1,8,1,234,30,97,0,1023,48,63,alp vir,EUV,2001-10-26 22:41:51,2001-10-26,EUV2001_299_22_41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,FUV2002_292_01_57_06_UVIS_C34ST_BRIGHT19001_PR...,1,1024,10,1,16,125,0,1023,27,36,eta uma,FUV,2002-10-19 01:57:06,2002-10-19,FUV2002_292_01_57
875,FUV2002_292_01_57_06_UVIS_C34ST_BRIGHT19001_PR...,1,1024,1,1,16,125,0,1023,0,26,eta uma,FUV,2002-10-19 01:57:06,2002-10-19,FUV2002_292_01_57
876,FUV2002_292_01_57_06_UVIS_C34ST_BRIGHT19001_PR...,1,1024,1,1,16,125,0,1023,37,63,eta uma,FUV,2002-10-19 01:57:06,2002-10-19,FUV2002_292_01_57
919,FUV2003_021_20_48_13_UVIS_C35ST_BRIGHT19001_PR...,1,1,64,23,1,38,0,1023,0,63,kap ori,FUV,2003-01-21 20:48:13,2003-01-21,FUV2003_021_20_48
920,FUV2003_021_20_48_53_UVIS_C35ST_BRIGHT19001_PR...,1,1024,1,302,1,39,0,1023,0,63,kap ori,FUV,2003-01-21 20:48:53,2003-01-21,FUV2003_021_20_48

In [ ]:
uvis = UVISObs("EUV2001_299_20_44")

In [ ]:
uvis.fuv

FUV2001_299_20_44.DAT
:   0%|          | 0/30539776 [00:00<?, ?it/s]

FUV2001_299_20_44.LBL
:   0%|          | 0/5103 [00:00<?, ?it/s]

FUV2001_299_20_44_CAL_3.DAT
:   0%|          | 0/262144 [00:00<?, ?it/s]

FUV2001_299_20_44_CAL_3.LBL
:   0%|          | 0/13799 [00:00<?, ?it/s]

TypeError: unsupported operand type(s) for //: 'int' and 'L'

In [ ]:
get_star_obs().dtypes

filename                 object
slit                      int64
nx                        int64
ny                        int64
nz                        int64
int                       int64
odcid                     int64
x1                        int64
x2                        int64
y1                        int64
y2                        int64
name                     object
detector                 object
filename_time    datetime64[ns]
date             datetime64[ns]
dtype: object

In [ ]:
# export
def get_spica_obs():
    "Filter Greg's list for Spica (alp vir) obs."
    return get_star_obs().query("name=='alp vir'")

In [ ]:
get_spica_obs().head()

,filename,slit,nx,ny,nz,int,odcid,x1,x2,y1,y2,name,detector,filename_time,date
0,EUV1999_016_19_47_15,2,1024,64,2,60,12,0,1023,0,63,alp vir,EUV,1999-01-16 19:47:15,1999-01-16
1,EUV1999_016_19_49_06,2,1024,1,123,1,13,0,1023,0,63,alp vir,EUV,1999-01-16 19:49:06,1999-01-16
2,EUV1999_016_20_08_10,2,1,64,399,1,11,0,1023,0,63,alp vir,EUV,1999-01-16 20:08:10,1999-01-16
3,EUV1999_016_20_16_14,2,1024,64,2,60,12,0,1023,0,63,alp vir,EUV,1999-01-16 20:16:14,1999-01-16
4,EUV1999_016_20_18_06,2,1024,1,123,1,13,0,1023,0,63,alp vir,EUV,1999-01-16 20:18:06,1999-01-16

In [ ]:
# export
def filter_spica_for_date(date: str):  # date in shape of yyyy-mm-dd
    return get_spica_obs().query("date==@date")

In [ ]:
filter_spica_for_date("1999-01-16").head()

,filename,slit,nx,ny,nz,int,odcid,x1,x2,y1,y2,name,detector,filename_time,date
0,EUV1999_016_19_47_15,2,1024,64,2,60,12,0,1023,0,63,alp vir,EUV,1999-01-16 19:47:15,1999-01-16
1,EUV1999_016_19_49_06,2,1024,1,123,1,13,0,1023,0,63,alp vir,EUV,1999-01-16 19:49:06,1999-01-16
2,EUV1999_016_20_08_10,2,1,64,399,1,11,0,1023,0,63,alp vir,EUV,1999-01-16 20:08:10,1999-01-16
3,EUV1999_016_20_16_14,2,1024,64,2,60,12,0,1023,0,63,alp vir,EUV,1999-01-16 20:16:14,1999-01-16
4,EUV1999_016_20_18_06,2,1024,1,123,1,13,0,1023,0,63,alp vir,EUV,1999-01-16 20:18:06,1999-01-16

In [ ]:
cat = CatalogFilter("2002-198")

Stored index is up-to-date.

In [ ]:
cat.nasadate

'2002-198'

In [ ]:
cat.df.START_TIME

product_id
HSP1999_007_16_53    1999-01-07 16:53:07.953
HDAC1999_007_16_31   1999-01-07 16:31:07.962
HDAC1999_007_16_33   1999-01-07 16:33:07.961
HDAC1999_007_16_36   1999-01-07 16:36:13.960
HDAC1999_007_16_42   1999-01-07 16:42:07.958
                               ...
FUV2017_258_07_15    2017-09-15 07:15:04.442
EUV2017_257_22_39    2017-09-14 22:39:54.016
EUV2017_258_04_31    2017-09-15 04:31:53.005
EUV2017_258_07_00    2017-09-15 07:00:27.697
EUV2017_258_07_15    2017-09-15 07:15:04.442
Name: START_TIME, Length: 203340, dtype: datetime64[ns]